In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
df = pd.read_csv("7-cyber_attack_data.csv")

In [4]:
df.head()

src_packet_rate  dst_packet_rate  avg_payload_size  connection_duration  \
0        -1.286132        -0.648334          1.044115            -0.469715   
1        -0.222224         2.083232          1.191114            -1.354527   
2        -0.431963         0.375745         -1.370334             0.819214   
3        -0.912633         0.986988         -0.690042             2.014628   
4        -0.367056         1.667892          0.879172             2.214276   

   tcp_flag_count  avg_interarrival_time  failed_login_attempts  \
0        0.789859              -0.083727              -1.647309   
1       -0.956992               1.696028              -1.070406   
2        0.345243               1.389447              -1.904130   
3       -0.442260               0.590347              -1.819353   
4        1.846338              -0.894047               1.543838   

   unusual_port_activity_score  session_entropy  avg_response_delay  \
0                    -1.316412         1.011910           -0.898063   
1                     0.981403        -1.628798            1.377594   
2                     1.292602         0.925545            0.232705   
3                     1.560938         0.823755            0.517762   
4                     0.931103        -1.015210            1.061845   

   attack_type  
0            2  
1            0  
2            0  
3            0  
4            1

In [5]:
X = df.drop("attack_type", axis=1)
y = df["attack_type"]

In [6]:
X

src_packet_rate  dst_packet_rate  avg_payload_size  connection_duration  \
0          -1.286132        -0.648334          1.044115            -0.469715   
1          -0.222224         2.083232          1.191114            -1.354527   
2          -0.431963         0.375745         -1.370334             0.819214   
3          -0.912633         0.986988         -0.690042             2.014628   
4          -0.367056         1.667892          0.879172             2.214276   
..               ...              ...               ...                  ...   
995        -2.496807         0.469077          0.095018            -0.216876   
996         0.826337         0.510897         -0.389013             0.753788   
997        -0.163846        -0.410725          0.739086            -0.102535   
998         1.749691        -1.124168          0.199807            -0.841018   
999        -0.247556        -1.170594         -1.140586             0.444490   

     tcp_flag_count  avg_interarrival_time  failed_login_attempts  \
0          0.789859              -0.083727              -1.647309   
1         -0.956992               1.696028              -1.070406   
2          0.345243               1.389447              -1.904130   
3         -0.442260               0.590347              -1.819353   
4          1.846338              -0.894047               1.543838   
..              ...                    ...                    ...   
995        1.451541              -0.341269              -1.752938   
996        0.282069               0.262201               0.159772   
997        0.002940              -0.189182              -1.703856   
998        0.182736               1.827622              -0.047775   
999       -0.125509              -0.635228               0.126535   

     unusual_port_activity_score  session_entropy  avg_response_delay  
0                      -1.316412         1.011910           -0.898063  
1                       0.981403        -1.628798            1.377594  
2                       1.292602         0.925545            0.232705  
3                       1.560938         0.823755            0.517762  
4                       0.931103        -1.015210            1.061845  
..                           ...              ...                 ...  
995                    -2.607297        -0.219750           -0.622575  
996                    -0.333163        -1.666029            0.538015  
997                     0.558305         1.089718           -0.266273  
998                     0.752557         0.322294           -0.173343  
999                     0.206362         1.843518           -0.814831  

[1000 rows x 10 columns]

In [7]:
y

0      2
1      0
2      0
3      0
4      1
      ..
995    2
996    1
997    0
998    1
999    2
Name: attack_type, Length: 1000, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=15)

In [12]:
from sklearn.linear_model import LogisticRegression

In [13]:
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [14]:
y_pred

array([2, 0, 0, 0, 2, 0, 1, 1, 2, 0, 2, 1, 2, 1, 0, 0, 2, 2, 0, 2, 0, 0,
       0, 1, 1, 1, 1, 2, 2, 2, 1, 0, 2, 2, 2, 2, 1, 2, 1, 0, 2, 1, 0, 2,
       1, 1, 2, 0, 0, 0, 2, 0, 1, 2, 0, 2, 1, 2, 2, 1, 0, 0, 0, 2, 1, 2,
       1, 0, 2, 0, 2, 0, 2, 1, 2, 0, 2, 1, 1, 2, 1, 0, 1, 2, 2, 0, 2, 2,
       1, 0, 1, 0, 0, 0, 1, 1, 2, 1, 1, 0, 1, 1, 1, 2, 1, 1, 1, 0, 0, 1,
       2, 1, 2, 1, 0, 1, 2, 0, 0, 1, 0, 0, 2, 1, 0, 1, 0, 2, 2, 1, 0, 2,
       2, 2, 1, 2, 0, 2, 0, 2, 1, 0, 2, 0, 2, 2, 0, 1, 1, 2, 1, 2, 1, 1,
       0, 0, 1, 1, 1, 2, 2, 0, 0, 2, 2, 1, 2, 1, 1, 1, 0, 0, 1, 0, 1, 2,
       0, 2, 2, 0, 2, 1, 1, 1, 2, 1, 0, 1, 0, 1, 1, 2, 0, 2, 1, 2, 1, 0,
       1, 2, 0, 2, 1, 0, 1, 0, 2, 1, 0, 1, 2, 0, 0, 0, 0, 0, 0, 1, 2, 0,
       2, 0, 2, 1, 2, 1, 0, 0, 1, 1, 2, 1, 0, 2, 1, 0, 2, 1, 1, 2, 2, 1,
       1, 2, 2, 1, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 0, 0, 1, 2, 1, 1, 2, 0,
       2, 0, 1, 0, 1, 2, 2, 1, 2, 2, 2, 2, 0, 2, 1, 0, 0, 0, 2, 1, 2, 2,
       2, 1, 0, 0, 2, 1, 2, 2, 1, 2, 1, 2, 1, 2])

In [15]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [16]:
print(f"score: \n{accuracy_score(y_test, y_pred)}")
print(f"classifictaion report:\n{classification_report(y_test, y_pred)}")
print(f"confusion matrix:\n{confusion_matrix(y_test, y_pred)}")

score: 
0.7866666666666666
classifictaion report:
              precision    recall  f1-score   support

           0       0.91      0.78      0.84       105
           1       0.73      0.74      0.73        97
           2       0.74      0.84      0.78        98

    accuracy                           0.79       300
   macro avg       0.79      0.79      0.79       300
weighted avg       0.80      0.79      0.79       300

confusion matrix:
[[82 17  6]
 [ 2 72 23]
 [ 6 10 82]]


In [18]:
penalty = ["l1", "l2","elasticnet"]
c_values = [100,10,1,0.1,0.01]
solver = ["newton-cg","lbfgs","liblinear","sag","saga","newton-cholesky"]
params = dict(penalty = penalty, C = c_values, solver = solver)


In [19]:
from sklearn.model_selection import GridSearchCV, StratifiedKFold

In [22]:
cv = StratifiedKFold()

In [23]:
grid = GridSearchCV(estimator=model, cv=cv, param_grid=params, scoring="accuracy", n_jobs=-1)

In [24]:
grid.fit(X_train, y_train)

c:\Users\Arda\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning: 
250 fits failed out of a total of 450.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\Arda\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Arda\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "c:\Users\Arda\AppData\

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga', 'newton-cholesky']},
             scoring='accuracy')

In [25]:
grid.best_params_

{'C': 0.1, 'penalty': 'l1', 'solver': 'liblinear'}

In [26]:
grid.best_score_

np.float64(0.7985714285714286)

In [27]:
y_pred = grid.predict(X_test)

In [28]:
print(f"score: \n{accuracy_score(y_test, y_pred)}")
print(f"classifictaion report:\n{classification_report(y_test, y_pred)}")
print(f"confusion matrix:\n{confusion_matrix(y_test, y_pred)}")


score: 
0.7866666666666666
classifictaion report:
              precision    recall  f1-score   support

           0       0.92      0.78      0.85       105
           1       0.75      0.71      0.73        97
           2       0.71      0.87      0.78        98

    accuracy                           0.79       300
   macro avg       0.80      0.79      0.79       300
weighted avg       0.80      0.79      0.79       300

confusion matrix:
[[82 15  8]
 [ 2 69 26]
 [ 5  8 85]]


In [29]:
from sklearn.multiclass import OneVsOneClassifier, OneVsRestClassifier

In [30]:
onevsoneModel = OneVsOneClassifier(LogisticRegression())
onevsrestModel = OneVsRestClassifier(LogisticRegression())

In [31]:
onevsoneModel.fit(X_train, y_train)
y_pred = onevsoneModel.predict(X_test)
print(f"score: \n{accuracy_score(y_test, y_pred)}")
print(f"classifictaion report:\n{classification_report(y_test, y_pred)}")
print(f"confusion matrix:\n{confusion_matrix(y_test, y_pred)}")


score: 
0.7966666666666666
classifictaion report:
              precision    recall  f1-score   support

           0       0.92      0.80      0.86       105
           1       0.76      0.74      0.75        97
           2       0.73      0.85      0.78        98

    accuracy                           0.80       300
   macro avg       0.80      0.80      0.80       300
weighted avg       0.81      0.80      0.80       300

confusion matrix:
[[84 12  9]
 [ 3 72 22]
 [ 4 11 83]]


In [32]:
onevsrestModel.fit(X_train, y_train)
y_pred = onevsrestModel.predict(X_test)
print(f"score: \n{accuracy_score(y_test, y_pred)}")
print(f"classifictaion report:\n{classification_report(y_test, y_pred)}")
print(f"confusion matrix:\n{confusion_matrix(y_test, y_pred)}")


score: 
0.7833333333333333
classifictaion report:
              precision    recall  f1-score   support

           0       0.91      0.79      0.85       105
           1       0.73      0.71      0.72        97
           2       0.72      0.85      0.78        98

    accuracy                           0.78       300
   macro avg       0.79      0.78      0.78       300
weighted avg       0.79      0.78      0.78       300

confusion matrix:
[[83 16  6]
 [ 2 69 26]
 [ 6  9 83]]
